# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('position', models.SmallIntegerField(default=0, verbose_name='posição')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_course', to='courses.Course', verbose_name='cursos')),
            ],
            options={
                'verbose_name_plural': 'videos',
                'verbose_name': 'video',
            },
        ),
    ]
