# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='título')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_course', to='courses.Course', verbose_name='cursos')),
            ],
            options={
                'verbose_name_plural': 'leituras',
                'verbose_name': 'leitura',
            },
        ),
    ]
