# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
    ]
