# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='position',
            field=models.SmallIntegerField(default=0, verbose_name='posição'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='url',
            field=models.URLField(default='u'),
            preserve_default=False,
        ),
    ]
