# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20170530_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
