# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.CharField(default='D', max_length=50, verbose_name='módulo'),
            preserve_default=False,
        ),
    ]
