# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_auto_20170512_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50, verbose_name='turma')),
                ('date_initial', models.DateField(blank=True, null=True, verbose_name='data inicial')),
                ('date_final', models.DateField(blank=True, null=True, verbose_name='data final')),
                ('short_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='breve descrição')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ('team',),
                'verbose_name_plural': 'turmas',
                'verbose_name': 'turma',
            },
        ),
        migrations.CreateModel(
            name='ClasseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classedetail', to='courses.Classe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classedet_user', to='authentication.Profile', verbose_name='aluno')),
            ],
            options={
                'ordering': ('classe',),
                'verbose_name_plural': 'detalhes',
                'verbose_name': 'detalhe',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'cursos',
                'verbose_name': 'curso',
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_course', to='courses.Course', verbose_name='curso'),
        ),
    ]
