# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date_start',), 'verbose_name': 'evento', 'verbose_name_plural': 'eventos'},
        ),
    ]
